### ISSUE TITLE
correction de ligne de défaut

### ISSUE THREAD

**Issue by celticwolf33** [OGSteam/mod-production#1]
Le mod s'ouvre avec une petite erreur que voici:
Warning: Missing argument 1 for find_nb_planete_user(), called in /volume1/web/ogspy/xxxxx/mod/production/production.php on line 18 and defined in /volume1/web/ogspy/xxxxx/includes/user.php on line 1111

Modification de l'entrée find_nb_planete_user() par find_nb_planete_user($user_data["user_id"]) et plus d'erreur.

**Comment by darknoon29** [comment]
Je vais essayer de faire ça ce soir

**Comment by darknoon29** [comment]
Corrigé et disponible sur autoupdate
