### ISSUE TITLE
Bug sur comptage total

### ISSUE THREAD

**Issue by Athar42** [OGSteam/mod-production#4]
Si l'on décoche une/des planètes du décompte final, celui-ci n'est pas pris en compte (infos du tableau "Production globale").

**Comment by satepestage** [comment]
Normalement, c'est corrigé avec la version 1.5.6-beta1 en cours de test.

**Comment by satepestage** [comment]
Corrigé.
Il faut utiliser la version 1.5.7 maintenant.
