### ISSUE TITLE
Mod non fonctionnel sur la 3.3.7

### ISSUE THREAD

**Issue by Steffronte** [OGSteam/mod-production#5]
Bonjour,

Le module est non fonctionnel sur la 3.3.7. Il y a des erreurs JavaScript dans la console, et la production n'est pas affichée.

![image](https://user-images.githubusercontent.com/61603453/76650647-56c2dc00-6563-11ea-840e-b70e7ce05e62.png)

![image](https://user-images.githubusercontent.com/61603453/76650537-1fecc600-6563-11ea-833c-2001aaad10a6.png)

**Comment by satepestage** [comment]
Bonjour,

Tu peux installer la version 1.5.7, tester de ton côté et nous faire un retour ?
Merci d'avance.

**Comment by satepestage** [comment]
Testé par d'autres membres.
